### ISSUE TITLE
3.4.2 TaintLess error and fix

### ISSUE THREAD

**Issue by NayooZ** [Jaliborc/Bagnon#1703]
- Addon version: 10.0.16
 - Server patch: 3.4.2.50063 (Classic WoTLK)

New error upon logging in after this morning's patch release.

```lua

1x [string "BagBrother/libs/TaintLess/..."]:77: hooksecurefunc(): GetAttribute is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "BagBrother/libs/TaintLess/TaintLess.xml:<Scripts>"]:77: in main chunk

Locals:
``` 
The included version of TaintLess lib is out of date - a fix for 3.4.2 was released and fixes this issue. Can be resolved by including the newest release from https://www.townlong-yak.com/addons/taintless/release/23-05-18

**Comment by tehKD** [comment]
Thank you

**Comment by d-schmidt** [comment]
The fix does work in retail 10.1 as well.

**Comment by Voc1f3ra** [comment]
I installed TaintLess but now I get new interface errors with Bagnon, wtb an update to the addon :/

**Comment by Luigee91** [comment]
How can i install this fix. Where do I put the files? Thanks

**Comment by tehKD** [comment]
Download the "TaintLess-23-05-18.zip" file, open it and drag the "TaintLess" folder in the "BagBrother\libs" folder overwriting the old one.

**Comment by Luigee91** [comment]
> Download the "TaintLess-23-05-18.zip" file, open it and drag the "TaintLess" folder in the "BagBrother\libs" folder overwriting the old one.

Thanks!

**Comment by xiibo** [comment]
Any chance you could fix Combuctor as well? I'm clueless to this kinda stuff
